#What's Good Saraf, this will be the file where I specify the versions of the applications we will be having dockerized and how they communicate through their ports
#As you can see right now it is only the Database but I will add the nginx deets soon



version: "3.7"

services:

  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_USER: Bingeworthy
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - drkiq-postgres:/var/lib/postgresql/data


  Bingeworthy:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: ./Bingeworthy
        target: /opt/app/drkiq
    ports:
      - '8010:8010'
    env_file:
      - .env


  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    depends_on:
      - Bingeworthy
    ports:
      - '8020:8020'

volumes:
  Bingeworthy-postgres:
