#What's Good Saraf, this will be the file where I specify the versions of the applications we will be having dockerized and how they communicate through their ports
#As you can see right now it is only the Database but I will add the nginx deets soon



version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/Bingeworthy
    ports:
      - "3000:3000"
    depends_on:
      - db

