#What's Good Saraf, this will be the file where I specify the versions of the applications we will be having dockerized
#basically another abstraction of the stack to make dockers job easier
#this deploys a node.js ruby on rails application and a postgreSQL database
#--PS. Still need to make the network tunnel for the two containers



version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/Bingeworthy
    ports:
      - "3000:3000"
    depends_on:
      - db

